# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1471c2338ee47bc8b1c155f26812d50b5046a00e538d2132e3fbb031108e332f16f49c6199ba1b9e306a9aeb53bbc6324dad39f7a7d0e96d272c105d47f7898

test:
  secret_key_base: ad96e34398300ec9eaffd1b7ca22edd7ec7a0d6e06d54a0b5d9858d42ce0ecee83c44252ef5e3d13c642b31c5717a4deebda0169a588218cddc28f5f67d3d459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
